// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"LL_VariableWindowMV","status":true,"description":"変数を画面にウィンドウで表示します。","parameters":{}},
{"name":"Galv_SimpleCrops","status":true,"description":"(v.1.4) シンプルな農業/栽培システムを導入できます","parameters":{"Crop Charset Name":"!Crops","Watered Time":"60","Watered Benefit":"5","Crop Priority":"0,0,1,1,1","Crop Under or Front Fix":"true"}},
{"name":"ChoiceListWithTimeLimit","status":true,"description":"選択肢に、時間制限を設定します。","parameters":{}},
{"name":"KMS_PassiveSkill","status":true,"description":"[v0.2.0] 習得すると常に効果を発揮するスキルを作成します。","parameters":{}},
{"name":"KMS_ExtendStatusScene","status":true,"description":"[v0.2.0] ステータス画面の表示内容を拡張します。","parameters":{"Display elements":"11-18","Display states":"11-18","Element icon index":"76, 64, 65, 66, 67, 68, 69, 70, 71, 72, 82, 84, 67, 75, 239, 190, 277, 72","Caption for element":"にんそうRPG クイズ正答率","Caption for state":"にんそうRPG プロジェクト達成率","Chart frame color":"rgba(128, 192, 255, 0.9)","Chart base color":"rgba(128, 192, 255, 0.6)","Chart line color":"rgba(128, 255, 128, 1)","Chart flash color C":"rgba(128, 255, 128, 0.2)","Chart flash color E":"rgba(128, 255, 128, 0.9)"}},
{"name":"DP_MapZoom","status":true,"description":"マップの拡大率を制御します。","parameters":{"Base Scale":"1","Encount Effect":"true","Camera Controll":"true","Weather Patch":"true","Picture Size Fixation":"true","Old Focus":"false"}},
{"name":"Galv_Tools","status":false,"description":"(v.1.3) マップ時にボタンでツールを切り替えて使用するシステムを導入します。","parameters":{"HUD Image":"toolhud","HUD XY":"710,520","HUD Icon XY":"50,50","Icon Size":"32,32","Initial Zoom":"2","Number Size":"18","Switch Left":"pagedown","Switch Right":"pageup","Use Tool":"alt","Gamepad Dash Button":"true"}}
];
