// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Galv_SimpleCrops","status":true,"description":"(v.1.4) シンプルな農業/栽培システムを導入できます","parameters":{"Crop Charset Name":"!Crops","Watered Time":"60","Watered Benefit":"5","Crop Priority":"0,0,1,1,1","Crop Under or Front Fix":"true"}},
{"name":"Galv_Tools","status":true,"description":"(v.1.3) マップ時にボタンでツールを切り替えて使用するシステムを導入します。","parameters":{"HUD Image":"toolhud","HUD XY":"710,520","HUD Icon XY":"50,50","Icon Size":"32,32","Initial Zoom":"2","Number Size":"18","Switch Left":"pagedown","Switch Right":"pageup","Use Tool":"alt","Gamepad Dash Button":"true"}}
];
